CLIENT_1:
  idx: 1
  dataset_name: BraTS2020 #Birds #STL10 #CelebA BraTS2020
  path_model_save_dir: /home/vault/btr0/btr0104h/collafuse/models/
  t_cut_ratio: 0.20
  model_type: DDPM # DDPM, IMAGEN
  celeb_a_attributes:
    - Blond_Hair
    - Brown_Hair
    - Black_Hair
    - Gray_Hair
    - Bald
  birds_attributes:
    - 1     # has_bill_shape::curved_(up_or_down)
    - 2     # has_bill_shape::dagger
    - 3     # has_bill_shape::hooked
    - 4     # has_bill_shape::needle
    - 5     # has_bill_shape::hooked_seabird
    - 6     # has_bill_shape::spatulate
    - 7     # has_bill_shape::all-purpose
    - 8     # has_bill_shape::cone
    - 9     # has_bill_shape::specialized

CLIENT_2:
  idx: 2
  dataset_name: BraTS2020 #Birds #STL10 #CelebA BraTS2020
  path_model_save_dir: /home/vault/btr0/btr0104h/collafuse/models/
  t_cut_ratio: 0.20
  model_type: DDPM # DDPM, IMAGEN
  celeb_a_attributes:
    - Wearing_Necklace
    - Wearing_Earrings
  birds_attributes:
    - 10   # has_wing_color::blue
    - 11   # has_wing_color::brown
    - 12   # has_wing_color::iridescent
    - 13   # has_wing_color::purple
    - 14   # has_wing_color::rufous
    - 15   # has_wing_color::grey
    - 16   # has_wing_color::yellow
    - 17   # has_wing_color::olive
    - 18   # has_wing_color::green
    - 19   # has_wing_color::pink
    - 20   # has_wing_color::orange
    - 21   # has_wing_color::black
    - 22   # has_wing_color::white
    - 23   # has_wing_color::red
    - 24   # has_wing_color::buff
  
CLIENT_3:
  idx: 3
  dataset_name: BraTS2020 #Birds #STL10 #CelebA BraTS2020
  path_model_save_dir: /home/vault/btr0/btr0104h/collafuse/models/
  t_cut_ratio: 0.20
  model_type: DDPM # DDPM, IMAGEN
  celeb_a_attributes:
    - Wavy_Hair
    - Straight_Hair
    - Bangs
  birds_attributes:
    - 25    # has_upperparts_color::blue
    - 26    # has_upperparts_color::brown
    - 27    # has_upperparts_color::iridescent
    - 28    # has_upperparts_color::purple
    - 29    # has_upperparts_color::rufous
    - 30    # has_upperparts_color::grey
    - 31    # has_upperparts_color::yellow
    - 32    # has_upperparts_color::olive
    - 33    # has_upperparts_color::green
    - 34    # has_upperparts_color::pink
    - 35    # has_upperparts_color::orange
    - 36    # has_upperparts_color::black
    - 37    # has_upperparts_color::white
    - 38    # has_upperparts_color::red
    - 39    # has_upperparts_color::buff

CLIENT_4:
  idx: 4
  dataset_name: BraTS2020 #Birds #STL10 #CelebA BraTS2020
  path_model_save_dir: /home/vault/btr0/btr0104h/collafuse/models/
  t_cut_ratio: 0.20
  model_type: DDPM # DDPM, IMAGEN
  celeb_a_attributes:
    - Bushy_Eyebrows
    - Arched_Eyebrows
  birds_attributes:
    - 59    # has_back_color::blue
    - 60    # has_back_color::brown
    - 61    # has_back_color::iridescent
    - 62    # has_back_color::purple
    - 63    # has_back_color::rufous
    - 64    # has_back_color::grey
    - 65    # has_back_color::yellow
    - 66    # has_back_color::olive
    - 67    # has_back_color::green
    - 68    # has_back_color::pink
    - 69    # has_back_color::orange
    - 70    # has_back_color::black
    - 71    # has_back_color::white
    - 72    # has_back_color::red
    - 73    # has_back_color::buff

CLIENT_5:
  idx: 5
  dataset_name: BraTS2020 #Birds #STL10 #CelebA BraTS2020
  path_model_save_dir: /home/vault/btr0/btr0104h/collafuse/models/
  t_cut_ratio: 0.20
  model_type: DDPM # DDPM, IMAGEN
  celeb_a_attributes:
  - Eyeglasses
  - Narrow_Eyes
  - Bags_Under_Eyes
  birds_attributes:
    - 136     # has_eye_color::blue
    - 137     # has_eye_color::brown
    - 138     # has_eye_color::purple
    - 139     # has_eye_color::rufous
    - 140     # has_eye_color::grey
    - 141     # has_eye_color::yellow
    - 142     # has_eye_color::olive
    - 143     # has_eye_color::green
    - 144     # has_eye_color::pink
    - 145     # has_eye_color::orange
    - 146     # has_eye_color::black
    - 147     # has_eye_color::white
    - 148     # has_eye_color::red
    - 149     # has_eye_color::buff
