args:
  time: 24:00:00                            # Wall clock time limit.
  ntasks: 4                                 # Number of tasks to be launched.
  partition: a100                           # Request a specific queue for the resource allocation.
  gres: gpu:1                               # Number of gpus: gpu:3
  export: NONE
  
  job: ./run_scripts/run_training_job.sh
  # salloc