BraTS2020:
  path_train_raw: data/BraTS2020/BraTS2020_TrainingData/RAW/
  path_test_raw: data/BraTS2020/BraTS2020_ValidationData/RAW/
  path_train_sliced: data/BraTS2020/BraTS2020_TrainingData/SLICED/
  path_test_sliced: data/BraTS2020/BraTS2020_ValidationData/SLICED/
  n_train_items: 369
  n_test_items: 125
  slice_min: 60
  slice_max: 100
  slice_axis: 2

CelebA:
  path_train_images: data/CelebA/RAW/
  path_test_images: data/CelebA/RAW/
  path_labels: data/CelebA/annotations/list_attr_celeba.txt
  path_text_embeds: data/CelebA/annotations/
  n_train_items: 2000
  n_test_items: 5000

STL10:
  path_train_images: data/stl10/RAW/
  path_labels: data/stl10/annotations/identity_stl10.txt
  path_text_embeds: data/stl10/annotations/
  n_train_items: 10 # classes and 202599 items
  n_test_items: 10 # classes and 0 items

Birds:
  path_train_images: data/Birds/images/
  path_labels: data/Birds/images.txt
  path_text_embeds: data/Birds/embeds/
  n_train_items: 2000
  n_test_items: 1000
