DEFAULT:
  n_epochs: 20                          # total training steps
  lr: 0.001
  initial_loss: 1.5
  display: False
  batch_size: 16
  t_cut_ratio: 0.5 
  loss_lambda: 0.5
  adam_betas: 
  - 0.9
  - 0.99
  save_and_sample_every: 1000
  num_samples: 25
  results_folder: ./src/assets/
  calculate_fid: False                  # whether to calculate fid during training
  inception_block_idx: 2048
  max_grad_norm: 1.
  num_fid_samples: 50000
  save_best_and_latest_only: False
  offset_noise_strength: 0