DEFAULT:
  n_epochs: 3                         # total training steps
  lr: 0.001
  initial_loss: 1.5
  display: False
  batch_size: 10
  num_workers: 2 
  loss_lambda: 0.5
  adam_betas: 
  - 0.9
  - 0.99
  save_and_sample_every: 1000
  num_samples: 25
  results_folder: ./results/
  calculate_performance: True          # whether to calculate fid during training
  offset_noise_strength: 0

GENERATION:
  sample_batch_size: 150
  n_samples: 4050
  return_all_timesteps: False
  create_new_samples: False