DEFAULT:
  n_epochs: 5                         # total training steps
  lr: 0.001
  initial_loss: 1.5
  display: True
  batch_size: 10
  num_workers: 1
  loss_lambda: 0.5
  adam_betas: 
  - 0.9
  - 0.99
  save_and_sample_every: 1000
  num_samples: 25
  results_folder: ./results/
  calculate_performance: True          # whether to calculate fid during training
  offset_noise_strength: 0
  load_existing_model: True

GENERATION:
  sample_batch_size: 10
  n_samples: 10
  return_all_timesteps: False
  create_new_samples: False