DEFAULT:
  n_epochs: 50                          # total training steps
  lr: 0.001
  initial_loss: 1.5
  display: True
  batch_size: 16
  num_workers: 0 
  loss_lambda: 0.5
  adam_betas: 
  - 0.9
  - 0.99
  save_and_sample_every: 1000
  num_samples: 25
  results_folder: ./results/
  calculate_fid: False                  # whether to calculate fid during training
  inception_block_idx: 2048
  max_grad_norm: 1.
  num_fid_samples: 50000
  save_best_and_latest_only: False
  offset_noise_strength: 0

GENERATION:
  sample_batch_size: 1
  return_all_timesteps: True